### PR TITLE
(untested) Display Receiving party

### PR DESCRIPTION
**Pull request by zigastegu**
Add a name of the receiving party.

USE CASE:
If you don't have a receiving party in Revolut Bank use the name for addition to the list.
I understand it could also be copied from RAW format.

### CODE REVIEW

**Comment by zigastegu** [comment]
Tried to test inside Chrome browser DevTools with overrides.
JS env is not my native environment :) so I don't really know what am I doing.

image

**Comment by zigastegu** [comment]
Ok, yes Overrides do work.
Just needed to modify "main.61180847.chunk.js" not "upnqr.js" directly as "*chunk.js" seems to actually be loaded.

**Review by maslick — APPROVED** [review]
LGTM

**Review by maslick — CHANGES_REQUESTED** [review]
Can you bump patch version in ``package.json`` (1.2.6 -> 1.2.7)? Other than that I am satisfied :)

**Comment by maslick** [comment]
@zigastegu are you going to contribute?

**Comment by maslick** [comment]
> Ok, yes Overrides do work. Just needed to modify "main.61180847.chunk.js" not "upnqr.js" directly as "*chunk.js" seems to actually be loaded.

Normally, you do not edit these files. It's like with a Java project, built with Maven. You edit files in `src` directory and not in `target`. Same here, you build the project with webpack, and it generates the resulting minified/uglified files in the build directory.

**Comment by zigastegu** [comment]
> @zigastegu are you going to contribute?

Sorry for slow response. I see you are active and I am blocking a bit.

**Review by maslick — APPROVED** [review]
excellent!

**Pull request merged**
